travis:
  secure:
    BINSTAR_TOKEN: LNNMKL8rWUP+tRqbZo1ijzaU5aDFhDSC0qPMnIb71c/QJudFfii/e5O1xYC0so2q58Dcc7BbxO4j03XkWPw2aV1tZ59NBPvKH96IVMbg6RoMFjiMv72Gc/73fAIZylPBe631mTnZG953wtl8piTm8WQEXNtxCn0TqTg9lBsCPc78wCqbHstLYVq9oUTMneBFcdhIhzKw02bpnKUvUU4Oa8y/I/uvTshK+KOFxysswwkEVAs2yXw8W/drQKogJH9nrUkMj007JXN96+J3f44vMBGnmplpdCJZFNP7xUFCwTFBkC7CbBRwQ3giMTVOEYCmgqL8cii7mv9/8KrXREuBZfxGMsSfAlIv6T8UCbtK+bBqZmCoHb1sT5jyH92PZrGAjN3CCu9Ha1PbtKBXgR1ljNjs/e59wUE1hCr6qygqZ6psHjUV70HOA9Hqs44CadOI+7I0Hwqf6uMj5+MdfwTMprlXKkp2DBaTo9TBC8NbpevfrBaH6pwFkz/F4zwpNraXMTjcazttRLS/o+bwIDLjxV4Zg52WSDcJtpmXBQphNWM2RiQ+mtzOSh4PWSu5LKSyjSaleyuNx0aBNeXx3K/ubMmKzBk7YRW0uwOJPONDjAOt2bw3aw/3JcufP2NxzulkkoFtfj2QKQ4ZOTcJdyu3OM0parEpJq5dPmrZ3XArQsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
